name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull and tag the Docker image
      run: |
        docker pull ruanfk2023/grupos-partidas-apis:tagname
        docker tag ruanfk2023/grupos-partidas-apis:tagname grupos-partidas-apis:$(date +%s)
